
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <link rel="stylesheet" type="text/css" href="images/bgimages.css">
</head>

<body>
<div class="container">   
<img src="images/R.Battery1.jpg" alt="Rectifier Backgroud">
    <div class="login-box">  
            <table border="0" width="403%">
                <tr height="188"> 
                    <th width="55px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th></th>
                </tr>
                <tr height="188">
                    <th width="55px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th></th>
                </tr>       
            </table> 
    </div>
    <div class="login-box2">  
            <table border="0" width="403%">
                <tr height="188"> 
                    <th width="55px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th></th>
                </tr>
                <tr height="188">
                    <th width="55px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th></th>
                </tr>       
            </table> 
    </div>
    
    <div class="login-box3">  
            <table border="0"  width="403%">
                <tr height="37.6"> 
                    <th width="55px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                    <th width="38px"></th>
                </tr>
                <tr height="37.6"> 
                <th width="55px"></th>
                <th width="38px"></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                </tr>
                <tr height="37.6"> 
                <th width="55px"></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                </tr>
                <tr height="37.6"> 
                <th width="55px"></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">5.1</th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th colspan="2" rowspan="2" align="center" style="font-size:70px;">
                        <a href="?page=rectifier21" class="nav-link">
                            <!--
                                <i class="fas fa-search"></i>
                            -->    
                            </a>
                    </th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                </tr>
                <tr height="37.6"> 
                <th width="55px"></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">7.1</th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                </tr>
                <tr height="37.6"> 
                <th width="55px"></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">9.1</th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                </tr>
                <tr height="37.6"> 
               <th width="55px"></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                    <th ></th>
                </tr>
            </table> 
    </div>    
    <!--
    <div class="login-box3">  
            <table border="5"  width="403%">
                <tr height="37.6"> 
                    <th width="55px">1.1</th>
                    <th width="38px">1.2</th>
                    <th width="38px">1.3</th>
                    <th width="38px">1.4</th>
                    <th width="38px">1.5</th>
                    <th width="38px">1.6</th>
                    <th width="38px">1.7</th>
                    <th width="38px">1.8</th>
                    <th width="38px">1.9</th>
                    <th width="38px">1.10</th>
                    <th width="38px">1.11</th>
                    <th width="38px">1.12</th>
                    <th width="38px">1.13</th>
                    <th width="38px">1.14</th>
                    <th width="38px">1.15</th>
                    <th width="38px">1.16</th>
                    <th width="38px">1.17</th>
                    <th width="38px">1.18</th>
                    <th width="38px">1.19</th>
                    <th width="38px">1.20</th>
                    <th width="38px">1.21</th>
                    <th width="38px">1.22</th>
                    <th width="38px">1.23</th>
                    <th width="38px">1.24</th>
                    <th width="38px">1.25</th>
                    <th width="38px">1.26</th>
                    <th width="38px">1.27</th>
                    <th width="38px">1.28</th>
                    <th width="38px">1.29</th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">2.1</th>
                <th width="38px">1.2</th>
                    <th >1.3</th>
                    <th >1.4</th>
                    <th >1.5</th>
                    <th >1.6</th>
                    <th >1.7</th>
                    <th >1.8</th>
                    <th >1.9</th>
                    <th >1.10</th>
                    <th >1.11</th>
                    <th >1.12</th>
                    <th >1.13</th>
                    <th >1.14</th>
                    <th >1.15</th>
                    <th >1.16</th>
                    <th >1.17</th>
                    <th >1.18</th>
                    <th >1.19</th>
                    <th >1.20</th>
                    <th >1.21</th>
                    <th >1.22</th>
                    <th >1.23</th>
                    <th >1.24</th>
                    <th >1.25</th>
                    <th >1.26</th>
                    <th >1.27</th>
                    <th >1.28</th>
                    <th >1.29</th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">3.1</th>
                    <th >1.2</th>
                    <th >1.3</th>
                    <th >1.4</th>
                    <th >1.5</th>
                    <th >1.6</th>
                    <th >1.7</th>
                    <th >1.8</th>
                    <th >1.9</th>
                    <th >1.10</th>
                    <th >1.11</th>
                    <th >1.12</th>
                    <th >1.13</th>
                    <th >1.14</th>
                    <th >1.15</th>
                    <th >1.16</th>
                    <th >1.17</th>
                    <th >1.18</th>
                    <th >1.19</th>
                    <th >1.20</th>
                    <th >1.21</th>
                    <th >1.22</th>
                    <th >1.23</th>
                    <th >1.24</th>
                    <th >1.25</th>
                    <th >1.26</th>
                    <th >1.27</th>
                    <th >1.28</th>
                    <th >1.29</th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">4.1</th>
                    <th >1.2</th>
                    <th >1.3</th>
                    <th >1.4</th>
                    <th >1.5</th>
                    <th >1.6</th>
                    <th >1.7</th>
                    <th >1.8</th>
                    <th >1.9</th>
                    <th >1.10</th>
                    <th >1.11</th>
                    <th >1.12</th>
                    <th >1.13</th>
                    <th >1.14</th>
                    <th >1.15</th>
                    <th >1.16</th>
                    <th >1.17</th>
                    <th >1.18</th>
                    <th >1.19</th>
                    <th >1.20</th>
                    <th >1.21</th>
                    <th >1.22</th>
                    <th >1.23</th>
                    <th >1.24</th>
                    <th >1.25</th>
                    <th >1.26</th>
                    <th >1.27</th>
                    <th >1.28</th>
                    <th >1.29</th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">5.1</th>
                    <th >1.2</th>
                    <th >1.3</th>
                    <th >1.4</th>
                    <th >1.5</th>
                    <th >1.6</th>
                    <th colspan="2" rowspan="2" align="center" style="font-size:30px;">
                        <a href="?page=rectifier21" class="nav-link">
                            <i class="fas fa-search"></i>
                        </a>
                    </th>
                    <th >1.9</th>
                    <th >1.10</th>
                    <th >1.11</th>
                    <th >1.12</th>
                    <th >1.13</th>
                    <th >1.14</th>
                    <th >1.15</th>
                    <th >1.16</th>
                    <th >1.17</th>
                    <th >1.18</th>
                    <th >1.19</th>
                    <th >1.20</th>
                    <th >1.21</th>
                    <th >1.22</th>
                    <th >1.23</th>
                    <th >1.24</th>
                    <th >1.25</th>
                    <th >1.26</th>
                    <th >1.27</th>
                    <th >1.28</th>
                    <th >1.29</th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">6.1</th>
                    <th >1.2</th>
                    <th >1.3</th>
                    <th >1.4</th>
                    <th >1.5</th>
                    <th >1.6</th>
                    <th >1.9</th>
                    <th >1.10</th>
                    <th >1.11</th>
                    <th >1.12</th>
                    <th >1.13</th>
                    <th >1.14</th>
                    <th >1.15</th>
                    <th >1.16</th>
                    <th >1.17</th>
                    <th >1.18</th>
                    <th >1.19</th>
                    <th >1.20</th>
                    <th >1.21</th>
                    <th >1.22</th>
                    <th >1.23</th>
                    <th >1.24</th>
                    <th >1.25</th>
                    <th >1.26</th>
                    <th >1.27</th>
                    <th >1.28</th>
                    <th >1.29</th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">7.1</th>
                    <th >1.2</th>
                    <th >1.3</th>
                    <th >1.4</th>
                    <th >1.5</th>
                    <th >1.6</th>
                    <th >1.7</th>
                    <th >1.8</th>
                    <th >1.9</th>
                    <th >1.10</th>
                    <th >1.11</th>
                    <th >1.12</th>
                    <th >1.13</th>
                    <th >1.14</th>
                    <th >1.15</th>
                    <th >1.16</th>
                    <th >1.17</th>
                    <th >1.18</th>
                    <th >1.19</th>
                    <th >1.20</th>
                    <th >1.21</th>
                    <th >1.22</th>
                    <th >1.23</th>
                    <th >1.24</th>
                    <th >1.25</th>
                    <th >1.26</th>
                    <th >1.27</th>
                    <th >1.28</th>
                    <th >1.29</th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">8.1</th>
                    <th >1.2</th>
                    <th >1.3</th>
                    <th >1.4</th>
                    <th >1.5</th>
                    <th >1.6</th>
                    <th >1.7</th>
                    <th >1.8</th>
                    <th >1.9</th>
                    <th >1.10</th>
                    <th >1.11</th>
                    <th >1.12</th>
                    <th >1.13</th>
                    <th >1.14</th>
                    <th >1.15</th>
                    <th >1.16</th>
                    <th >1.17</th>
                    <th >1.18</th>
                    <th >1.19</th>
                    <th >1.20</th>
                    <th >1.21</th>
                    <th >1.22</th>
                    <th >1.23</th>
                    <th >1.24</th>
                    <th >1.25</th>
                    <th >1.26</th>
                    <th >1.27</th>
                    <th >1.28</th>
                    <th >1.29</th>
                </tr>
                <tr height="37.6"> 
                <th width="55px">9.1</th>
                    <th >1.2</th>
                    <th >1.3</th>
                    <th >1.4</th>
                    <th >1.5</th>
                    <th >1.6</th>
                    <th >1.7</th>
                    <th >1.8</th>
                    <th >1.9</th>
                    <th >1.10</th>
                    <th >1.11</th>
                    <th >1.12</th>
                    <th >1.13</th>
                    <th >1.14</th>
                    <th >1.15</th>
                    <th >1.16</th>
                    <th >1.17</th>
                    <th >1.18</th>
                    <th >1.19</th>
                    <th >1.20</th>
                    <th >1.21</th>
                    <th >1.22</th>
                    <th >1.23</th>
                    <th >1.24</th>
                    <th >1.25</th>
                    <th >1.26</th>
                    <th >1.27</th>
                    <th >1.28</th>
                    <th >1.29</th>
                </tr>
                <tr height="37.6"> 
               <th width="55px">10.1</th>
                    <th >1.2</th>
                    <th >1.3</th>
                    <th >1.4</th>
                    <th >1.5</th>
                    <th >1.6</th>
                    <th >1.7</th>
                    <th >1.8</th>
                    <th >1.9</th>
                    <th >1.10</th>
                    <th >1.11</th>
                    <th >1.12</th>
                    <th >1.13</th>
                    <th >1.14</th>
                    <th >1.15</th>
                    <th >1.16</th>
                    <th >1.17</th>
                    <th >1.18</th>
                    <th >1.19</th>
                    <th >1.20</th>
                    <th >1.21</th>
                    <th >1.22</th>
                    <th >1.23</th>
                    <th >1.24</th>
                    <th >1.25</th>
                    <th >1.26</th>
                    <th >1.27</th>
                    <th >1.28</th>
                    <th >1.29</th>
                </tr>
            </table> 
    </div>
-->
</div>      
</body>
</html>